name: Deploy Docker App to Hostinger

on:
  push:
    branches:
      - main  # Triggers the redeployment when code hits the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Hostinger VPS
        uses: hostinger/vps-deploy-action@v1 # Official Hostinger deployment utility
        with:
          api_key: ${{ secrets::HOSTINGER_API_KEY }}
          vm_id: ${{ secrets::HOSTINGER_VM_ID }}
